### Data Wrangling with Pandas Assignment problems
#### Problem-1

### 1.Read in the covid19_cases.csv file

In [3]:
import pandas as pd
url="https://raw.githubusercontent.com/svkarthik86/Advanced-python/main/WEEK-8%20Assignment/covid19_cases.csv"
covid19_cases=pd.read_csv(url)
covid19_cases

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
0,01/01/2020,1,1,2020,0,0,Lithuania,LT,LTU,2794184.0,Europe,NaN
1,01/01/2020,1,1,2020,0,0,Iceland,IS,ISL,356991.0,Europe,NaN
2,01/01/2020,1,1,2020,0,0,Nepal,NP,NPL,28608715.0,Asia,NaN
3,01/01/2020,1,1,2020,0,0,San_Marino,SM,SMR,34453.0,Europe,NaN
4,01/01/2020,1,1,2020,0,0,Canada,CA,CAN,37411038.0,America,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
43438,18/09/2020,18,9,2020,822,2,Denmark,DK,DNK,5806081.0,Europe,69.220529
43439,18/09/2020,18,9,2020,4326,84,Iraq,IQ,IRQ,39309789.0,Asia,153.513925
43440,18/09/2020,18,9,2020,90,0,Bahamas,BS,BHS,389486.0,America,203.088173
43441,18/09/2020,18,9,2020,0,0,Isle_of_Man,IM,IMN,84589.0,Europe,3.546560
43442,18/09/2020,18,9,2020,34,8,Australia,AU,AUS,25203200.0,Oceania,3.031361

In [4]:
type(covid19_cases)

pandas.core.frame.DataFrame

### 2.Create a date column using the data in the dateRep column and the pd.to_datetime() function.

In [16]:
covid19_cases['Date']=pd.to_datetime(covid19_cases[["year","month","day"]])
covid19_cases

,year,dateRep,day,month,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000,Date
0,2020,01/01/2020,1,1,0,0,Lithuania,LT,LTU,2794184.0,Europe,NaN,2020-01-01
1,2020,01/01/2020,1,1,0,0,Iceland,IS,ISL,356991.0,Europe,NaN,2020-01-01
2,2020,01/01/2020,1,1,0,0,Nepal,NP,NPL,28608715.0,Asia,NaN,2020-01-01
3,2020,01/01/2020,1,1,0,0,San_Marino,SM,SMR,34453.0,Europe,NaN,2020-01-01
4,2020,01/01/2020,1,1,0,0,Canada,CA,CAN,37411038.0,America,NaN,2020-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...
43438,2020,18/09/2020,18,9,822,2,Denmark,DK,DNK,5806081.0,Europe,69.220529,2020-09-18
43439,2020,18/09/2020,18,9,4326,84,Iraq,IQ,IRQ,39309789.0,Asia,153.513925,2020-09-18
43440,2020,18/09/2020,18,9,90,0,Bahamas,BS,BHS,389486.0,America,203.088173,2020-09-18
43441,2020,18/09/2020,18,9,0,0,Isle_of_Man,IM,IMN,84589.0,Europe,3.546560,2020-09-18
43442,2020,18/09/2020,18,9,34,8,Australia,AU,AUS,25203200.0,Oceania,3.031361,2020-09-18

### 3.Set the date column as the index and sort the index.

In [23]:
covid19_cases_pivot=covid19_cases.pivot(index="Date",columns="countriesAndTerritories",values="cases").fillna(0)
covid19_cases_pivot

countriesAndTerritories,Afghanistan,Albania,Algeria,Andorra,Angola,Anguilla,Antigua_and_Barbuda,Argentina,Armenia,Aruba,...,United_States_Virgin_Islands,United_States_of_America,Uruguay,Uzbekistan,Venezuela,Vietnam,Western_Sahara,Yemen,Zambia,Zimbabwe
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-09-14,75.0,168.0,247.0,0.0,56.0,0.0,0.0,10778.0,187.0,52.0,...,0.0,33871.0,28.0,578.0,910.0,3.0,0.0,2.0,73.0,18.0
2020-09-15,99.0,167.0,242.0,94.0,53.0,0.0,0.0,9056.0,107.0,14.0,...,1.0,34841.0,4.0,572.0,1029.0,0.0,0.0,0.0,181.0,5.0
2020-09-16,40.0,152.0,238.0,0.0,51.0,0.0,0.0,9908.0,150.0,92.0,...,11.0,51473.0,15.0,584.0,1086.0,0.0,0.0,3.0,99.0,45.0
2020-09-17,17.0,144.0,232.0,0.0,130.0,0.0,0.0,11893.0,257.0,176.0,...,6.0,24598.0,29.0,609.0,761.0,0.0,0.0,4.0,68.0,22.0
2020-09-18,0.0,132.0,228.0,45.0,180.0,0.0,0.0,11674.0,295.0,54.0,...,0.0,43567.0,20.0,609.0,868.0,3.0,0.0,3.0,41.0,35.0

### 4.Replace occurrences of United_States_of_America and United_Kingdom with USA and UK, respectively.

In [26]:
covid19_cases_pivot.columns=covid19_cases_pivot.columns.str.replace("United_States_of_America","USA")
covid19_cases_pivot.columns=covid19_cases_pivot.columns.str.replace("United_Kingdom","UK")
covid19_cases_pivot

countriesAndTerritories,Afghanistan,Albania,Algeria,Andorra,Angola,Anguilla,Antigua_and_Barbuda,Argentina,Armenia,Aruba,...,United_States_Virgin_Islands,USA,Uruguay,Uzbekistan,Venezuela,Vietnam,Western_Sahara,Yemen,Zambia,Zimbabwe
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-09-14,75.0,168.0,247.0,0.0,56.0,0.0,0.0,10778.0,187.0,52.0,...,0.0,33871.0,28.0,578.0,910.0,3.0,0.0,2.0,73.0,18.0
2020-09-15,99.0,167.0,242.0,94.0,53.0,0.0,0.0,9056.0,107.0,14.0,...,1.0,34841.0,4.0,572.0,1029.0,0.0,0.0,0.0,181.0,5.0
2020-09-16,40.0,152.0,238.0,0.0,51.0,0.0,0.0,9908.0,150.0,92.0,...,11.0,51473.0,15.0,584.0,1086.0,0.0,0.0,3.0,99.0,45.0
2020-09-17,17.0,144.0,232.0,0.0,130.0,0.0,0.0,11893.0,257.0,176.0,...,6.0,24598.0,29.0,609.0,761.0,0.0,0.0,4.0,68.0,22.0
2020-09-18,0.0,132.0,228.0,45.0,180.0,0.0,0.0,11674.0,295.0,54.0,...,0.0,43567.0,20.0,609.0,868.0,3.0,0.0,3.0,41.0,35.0

### 5.Using the countriesAndTerritories column, filter the data down to Argentina, Brazil, China, Colombia, India, Italy, Mexico, Peru, Russia, Spain, Turkey, the UK, and the USA.

In [27]:
covid19_cases_pivot.filter(["Argentina", "Brazil", "China", "Colombia", "India", "Italy", "Mexico", "Peru", "Russia", "Spain", "Turkey", "UK", "USA"])
covid19_cases_pivot

countriesAndTerritories,Afghanistan,Albania,Algeria,Andorra,Angola,Anguilla,Antigua_and_Barbuda,Argentina,Armenia,Aruba,...,United_States_Virgin_Islands,USA,Uruguay,Uzbekistan,Venezuela,Vietnam,Western_Sahara,Yemen,Zambia,Zimbabwe
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-09-14,75.0,168.0,247.0,0.0,56.0,0.0,0.0,10778.0,187.0,52.0,...,0.0,33871.0,28.0,578.0,910.0,3.0,0.0,2.0,73.0,18.0
2020-09-15,99.0,167.0,242.0,94.0,53.0,0.0,0.0,9056.0,107.0,14.0,...,1.0,34841.0,4.0,572.0,1029.0,0.0,0.0,0.0,181.0,5.0
2020-09-16,40.0,152.0,238.0,0.0,51.0,0.0,0.0,9908.0,150.0,92.0,...,11.0,51473.0,15.0,584.0,1086.0,0.0,0.0,3.0,99.0,45.0
2020-09-17,17.0,144.0,232.0,0.0,130.0,0.0,0.0,11893.0,257.0,176.0,...,6.0,24598.0,29.0,609.0,761.0,0.0,0.0,4.0,68.0,22.0
2020-09-18,0.0,132.0,228.0,45.0,180.0,0.0,0.0,11674.0,295.0,54.0,...,0.0,43567.0,20.0,609.0,868.0,3.0,0.0,3.0,41.0,35.0

### Problem-2
In order to determine the case totals per country efficiently, we need the aggregation skills , so the ECDC data in the covid19_cases.csv file has been aggregated for us and saved in the covid19_total_cases.csv file. It contains the total number of case per country. Use this data to find the 20 countries with the largest COVID-19 case totals. Hints: (Get covid19_total_cases.csv file using this link: https://raw.githubusercontent.com/svkarthik86/Advanced-python/main/WEEK-8%20Assignment/covid19_total_cases.csv)

When reading in the CSV file, pass in index_col='index'.
Note that it will be helpful to transpose the data before isolating the countries.

In [29]:
covid19_cases=pd.read_csv("https://raw.githubusercontent.com/svkarthik86/Advanced-python/main/WEEK-8%20Assignment/covid19_total_cases.csv",index_col="index").T

covid19_cases.sort_values(by="cases", ascending=False)[:20]
covid19_cases

index           cases
Afghanistan     38919
Albania         12073
Algeria         49413
Andorra          1564
Angola           3789
...               ...
Vietnam          1068
Western_Sahara    766
Yemen            2024
Zambia          14022
Zimbabwe         7647

[210 rows x 1 columns]